# Generated by Django 3.0 on 2019-12-08 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='サムネイル')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開可能か?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nblog2.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='画像')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='インデックス')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nblog2.Note', verbose_name='どのBookのページ?')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
