# Generated by Django 3.0 on 2019-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default='hello', verbose_name='大雑把な説明'),
            preserve_default=False,
        ),
    ]
