# Generated by Django 3.0.2 on 2020-02-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog2', '0003_auto_20191212_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, verbose_name='本文'),
        ),
    ]
