# Generated by Django 3.0.2 on 2020-02-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nblog2', '0004_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
